#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Lily Acadia Gilbert"
email = "lily@informedk12.com"

[aliases]
a = ["bookmark", "advance"]
bc = ["bookmark", "create"]
c = ["commit"]
ci = ["commit", "-i"]
d = ["diff"]
dm = ["diff", "-r", "main..@"]
lp = ["log", "-r", "::main", "--no-graph", "-p"]
e = ["edit"]
f = ["git", "fetch"]
fa = ["util", "exec", "/Users/lily/.config/jj/scripts/fetch_and_rebase.sh"]
logm = ["log", "-r", "::main"]
p = ["util", "exec", "/Users/lily/.config/jj/scripts/push_nearest.sh"]
pa = ["git", "push", "--tracked"]
pr = ["util", "exec", "/Users/lily/.config/jj/scripts/create_pr.sh"]
r = ["restore"]
ri = ["restore", "-i"]
s = ["squash"]
si = ["squash", "-i"]
lint = ["util", "exec", "/Users/lily/.config/jj/scripts/lint.sh"]

[revsets]
bookmark-advance-to = "latest(::@ & ~description(''))" # most recent with description

[revset-aliases]
'mine_since(start)' = "roots(start:: & mine() ~ immutable())"
'previous_bookmark(start)' = "heads(::start & bookmarks()) ~ main ~ staging"
'previous_bookmark(start, minus)' = "heads(::start & bookmarks())- ~ main ~ staging"

[template-aliases]
'change_id_pipe' = 'self.change_id().short() ++ "|"'
'bookmark_name' = 'bookmarks.map(|b| b.name()).join(" ")'

[remotes.origin]
auto-track-created-bookmarks = "*"

[ui]
pager = "delta"
diff-editor = ":builtin"
diff-formatter = ":git"

[merge-tools.diffconflicts]
program = "nvim"
merge-args = [
  "-c", "let g:jj_diffconflicts_marker_length=$marker_length",
  "-c", "JJDiffConflicts!", "$output", "$base", "$left", "$right",
]
merge-tool-edits-conflict-markers = true
