#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Lily Acadia Gilbert"
email = "lily@informedk12.com"

[aliases]
a = ["bookmark", "advance"]
bc = ["bookmark", "create"]
c = ["commit"]
ci = ["commit", "-i"]
d = ["diff"]
e = ["edit"]
r = ["rebase"]
s = ["squash"]
si = ["squash", "-i"]
logm = ["log", "-r", "::main"]
pr = [
  "util", "exec", "--", "bash", "-c", """
  bookmark=$(jj log --no-graph -r "ancestors(@) & bookmarks()" -T 'bookmarks')
  gh pr create --fill --draft --assignee "@me" --head "$bookmark"
  """
]

[remotes.origin]
auto-track-created-bookmarks = "*"

[ui]
diff-editor = ":builtin"

[fix.tools.rubocop]
command = ["rubocop", "--stdin", "$path", "--autocorrect-all", "--force-exclusion",
           "--format", "quiet", "--stderr"]
patterns = ["glob:'**/*.rb'"]

[fix.tools.haml-lint]
command = ["haml-lint", "--stderr", "$path"]
patterns = ["glob:'**/*.haml'"]

[fix.tools.eslint]
command = ["pnpm", "eslint", "--cache", "--fix-to-stdout", "--stdin", "--stdin-filename", "$path"]
patterns = ["glob:'**/*.ts'", "glob:'**/*.tsx'"]

# All of these next entries are to get delta working in jjui as well as jj diff
[[--scope]]
"--when.commands" = ["diff", "show"]

[--scope.ui]
pager = "delta"
diff-formatter = "delta"

[custom_commands]
"delta" = { args = [
  "util", "exec", "--", "bash", "-c", """
  jj show -r $change_id --summary --git --color=always | delta --pager 'less -R'
  """,
], show = "interactive" }
