#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Lily Acadia Gilbert"
email = "lily@informedk12.com"

[aliases]
a = ["bookmark", "advance"]
bc = ["bookmark", "create"]
c = ["commit"]
ci = ["commit", "-i"]
d = ["diff"]
dm = ["diff", "-r", "main..@"]
e = ["edit"]
r = ["rebase", "-b", "bookmarks() ~ main & mine()", "-d", "main", "--skip-emptied"]
s = ["squash"]
si = ["squash", "-i"]
logm = ["log", "-r", "::main"]
p = ["git", "push", "--tracked"]
pr = [
  "util", "exec", "--", "bash", "-c", """

  BOOKMARK=$(jj log --no-graph -r "heads((::@ & bookmarks()) ~ main ~ staging)" -T 'bookmarks')
  BOOKMARK=$(echo "$BOOKMARK" | sed "s/\\*\\$//")

  if [[ -z "$BOOKMARK" ]]; then
    echo "No bookmark found"
    exit 1
  fi

  PARENT_BOOKMARK=$(
    jj log \
    --no-graph \
    -r "heads((::@ & bookmarks()) ~ heads(::@ & bookmarks()) ~ main ~ staging)" -T 'bookmarks'
  )
  PARENT_BOOKMARK=$(echo "$PARENT_BOOKMARK" | sed "s/\\*\\$//")

  if [[ -z "$PARENT_BOOKMARK" ]]; then
    gh pr create --fill --draft --assignee "@me" --head "$BOOKMARK"
  else
    gh pr create --fill --draft --assignee "@me" --base "$PARENT_BOOKMARK" --head "$BOOKMARK"
  fi
  """
]
lint = [
  "util", "exec", "--", "sh", "-c", """
    jj diff --name-only -r main..@ -- 'root-glob:**/*.rb' | \
      xargs rubocop -A --force-exclusion
    jj diff --name-only -r main..@ -- "root-glob:'**/*.{js,jsx,ts,tsx}'" | \
      xargs ./node_modules/eslint/bin/eslint.js --cache --fix
    jj diff --name-only -r main..@ -- 'root-glob:**/*.haml' | \
      xargs haml-lint
  """
]

[revsets]
bookmark-advance-to = "coalesce((@ & ~empty()), @-)"

[remotes.origin]
auto-track-created-bookmarks = "*"

[ui]
pager = "delta"
diff-editor = ":builtin"
diff-formatter = ":git"
