# Helpful commands
# ctrl + shift + g  -- Open last output in pager
# ctrl + shift + x  -- Jump back to previous ran command
# ctrl + shift + z  -- Jump forward to next ran command

font_family            Monaco
bold_font              Monaco
italic_font            Monaco Italic
bold_italic_font       Monaco Bold Italic
cursor_blink_interval  0

font_size              14.0
inactive_text_alpha    0.5
modify_font cell_width 90%
map cmd+minus          change_font_size all -1.0
map cmd+plus           change_font_size all +1.0

copy_on_select         yes

wheel_scroll_multiplier 1.0

enabled_layouts        horizontal,stack
map cmd+enter          toggle_layout stack
map cmd+shift+enter    toggle_layout stack

map cmd+d              new_window
map cmd+left           previous_tab
map cmd+right          next_tab
map cmd+h              previous_window
map cmd+l              next_window
map cmd+shift+h        move_window_backward
map cmd+shift+l        move_window_forward

tab_bar_align          left
tab_bar_edge           top
tab_bar_style          powerline
tab_powerline_style    round
tab_title_template     "{fmt.fg.red}{fmt.fg.tab}Window {index}"
window_padding_width   5 0 0 5

map page_up scroll_page_up
map page_down scroll_page_down

# Catppuccin-Frappe
include current-theme.conf
